### ISSUE TITLE
Вынести все литералы в const и присвоить понятные имена

### ISSUE THREAD

**Issue by coursar** [andreykhabarov/Bonus#1]
https://github.com/andreykhabarov/Bonus/blob/6f8cc34b497ddfb5bee6cba400b0f6c5ddad3068/src/js/lib.js#L4-L5

**Comment by andreykhabarov** [comment]
@coursar 
https://github.com/andreykhabarov/Bonus/blob/30cd8946dc2d302e965315f9d3ce1bc5100fb996/src/js/lib.js#L1-L14
